name = "TensorNetworkSolvers"
uuid = "62d5c68e-057c-4e85-9e57-968d0954630a"
version = "0.1.0"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
AlgorithmsInterface = "d1e3940c-cd12-4505-8585-b0a4b322527d"

[compat]
AlgorithmsInterface = "0.1"
julia = "1.10"
