[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
TensorNetworkSolvers = "62d5c68e-057c-4e85-9e57-968d0954630a"

[sources]
TensorNetworkSolvers = {path = ".."}

[compat]
Graphs = "1"
TensorNetworkSolvers = "0.1"
